name: Build LaTeX CV on Release

on:
  release:
    types: [published]  # Only run when a new release is published

concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.tag_name }}
  cancel-in-progress: true

env:
  file_name: Zepeda_resume.pdf
  latex_file: main.tex

jobs:
  compile-latex-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get full history and tags

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.latex_file }}
          latexmk_use_xelatex: true

      - name: Check output
        run: ls -la

      - name: Change PDF name
        run: mv main.pdf ${{ env.file_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ${{ env.file_name }}
